### ISSUE TITLE
Security/Safety

### ISSUE THREAD

**Issue by KateOStrofik** [sfdx-mass-action-scheduler/sfdx-mass-action-scheduler#143]
Hi! 
First off, THANK YOU SO MUCH for building and sharing this amazing tool! I became a very quick fan and think it's the best thing since sliced bread :)

I tried to find security information before coming here to bug you, but couldn't find what I'm looking for. I have a client for whom I'd like to install the Mass Action Scheduler, but they wanted to know what data this tool touches and what it stores. This client's org has a great deal of sensitive data in it, so they are very cautious about 3rd party installs and have asked me to look into this further before installing the managed package in their org. 

Thank you!

**Comment by melinarobinson** [comment]
Kate, did you get a response? I would like some information on this as well. I LOVE the tool, but we have to protect our PII data and our Info Sec team is very strict.

**Comment by douglascayers** [comment]
👋 Hi, and thank you for your interest in Mass Action Scheduler!

The app only performs queries and actions on data that you configure in your Salesforce org (e.g. reports or list views or process builders or apex).

Mass Action Scheduler is a tool to run those data sources for you then pass the data to your selected actions.

The app stores the configuration and those field mappings in Mass Action Configuration records, which is what you as the admin use to create the automations.

The app is 100% hosted in your Salesforce org as if you had developed the Apex, Visualforce, and Aura components yourself.

The app is completely open source. Your security teams are welcome to analyze the code in this repository.

As with any customizations in a Salesforce org, I recommend that you use a sandbox and perform your testing their. Once confident, then install and use it in production.

Thanks
