### ISSUE TITLE
OAuth Error when resaving the Named Credential

### ISSUE THREAD

**Issue by ElissaBradley** [sfdx-mass-action-scheduler/sfdx-mass-action-scheduler#179]
I am setting up Mass Action Scheduler in a sandbox.  I ran the automated setup but when I edit/save the Named Credential, I get an OAuth error, with the following detail in my browser: 

error=invalid_client_id&error_description=client%20identifier%20invalid

My Named Credential looks like this: 
![Screenshot (207)](https://user-images.githubusercontent.com/92596959/211564950-4d3528e3-9960-4e6c-9f0f-2190767adffc.png)

I admit to mucking with this a bit - originally I was receiving the following error: 

ErrorCode=No_OauthToken&ErrorDescription=invalid_client+invalid+client+credentials&ProviderId=0SO020000008OaJ

I attempted to delete/recreate the Connected App, Auth. Provider, and Named Credential so that I could re-run the automated setup.  I was unable to successfully delete the Connected App, so ultimately I needed to create the Named Credential manually.  

I am running Version 2.4.  

I tried to run Mass Action Scheduler without a named credential but the batch fails with two empty error logs: Started/Finished. 

In another sandbox (created at the same time as this one) I was successfully able to authenticate and run one of my MAS configs.  (in this other sandbox I was also unable to run Mass Action Scheduler without a named credential.)

Thanks for your help with this.

**Comment by douglascayers** [comment]
This should now be resolved in version 2.5. Link with updated package id is available on the [release notes](https://github.com/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler/wiki/Release-Notes) page.

**Comment by ElissaBradley** [comment]
Great!!  Thank you so much.On Mar 15, 2023, at 3:06 AM, Doug Ayers ***@***.***> wrote:﻿
This should now be resolved in version 2.5. Link with updated package id is available on the release notes page.
