### ISSUE TITLE
Problem during Named Credential OAuth on Spring'23

### ISSUE THREAD

**Issue by ubersimple-brad** [sfdx-mass-action-scheduler/sfdx-mass-action-scheduler#180]
## Summary
When saving the Named Credential (after the 10 minute propagation period) in a Sandbox (with enhanced domains) the OAuth allows you to select the "Allow" button and creates an OAuth record for the user, however fails on the next screen showing message "Problem Logging In - - We can’t log you in because of an authentication error. For help, contact your Salesforce administrator."
![image](https://user-images.githubusercontent.com/2340060/212722365-bc6533ea-4569-4c63-af48-62c6a2a74bc1.png)

## Version of Mass Action Scheduler
Version 2.4

## Steps To Reproduce

1. In a Sandbox, Remove: Auth Provider, Named Credential, Connected App
2. Use Button on Mass Action Setup to auto create: Auth Provider, Named Credential, Connected App
3. Wait 10 minutes for Named Cred propagation
4. Edit/Save Named Credential > Login as Sandbox Admin > Click ALLOW > (then problem message appears)

1. List steps that cause the issue
2. Screen shots are also helpful
OAuth is created on user: 
![image](https://user-images.githubusercontent.com/2340060/212722915-cdd5952e-c6f0-4add-b309-db4c46580598.png)

Login issues present as no Consumer Key: 
![image](https://user-images.githubusercontent.com/2340060/212722963-eca88d6f-c7d1-4bb9-bc2a-b178c89fa7be.png)

## Expected Behavior
Should have logged in successfully

## Actual Result
Created OAuth, but failed to login in

## Does your configuration use Named Credentials?
Yes - and for safety would like to have Named Credentials on Each routine. As a work around, we can limit who edits the Mass Actions.

**Comment by lynguyenkhang** [comment]
Hi @ubersimple-brad, 

Could you let me know if you fixed this issue? When using auto-creating Auth Provider and Connected App, there are different Consumer Keys. But in [Setup manually Named Credentials](https://github.com/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler/wiki/Specify-the-Running-User-via-Named-Credentials) document, these consumer keys must be same. So, I change the consumer key in Auth Provider as one in Connected App. And I pass this issue

**Comment by douglascayers** [comment]
This should now be resolved in version 2.5. Link with updated package id is available on the [release notes](https://github.com/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler/wiki/Release-Notes) page.
